server:
  port: 9001

spring:
  application:
    name: tens-base
  datasource:
    url: jdbc:mysql://192.168.110.132:3306/tensquare_base?characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: rootswan
  jpa:
    database: mysql
    show-sql: true
  rabbitmq: 
    host: 192.168.110.132

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:7000/eureka   # 指定注册中心
    instance:
      prefer‐ip‐address: true   # 模块之间可以跨域访问
