server: 
  port: 9008
spring: 
  application:  
    name: tens-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.110.132:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: rootswan
  jpa: 
    database: MySQL
    show-sql: true
  redis:
    host: 192.168.110.132
  rabbitmq:
    host: 192.168.110.132
jwt:
  config:
    key: swan
    time: 60000


eureka:
  client:
    service‐url:
      defaultZone: http://localhost:7000/eureka   # 指定注册中心
    instance:
      prefer‐ip‐address: true   # 模块之间可以跨域访问