server:
  port: 9011

spring:
  application:
    name: tens‐web

eureka:
  client:
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:7000/eureka/
    instance:
      prefer‐ip‐address: true

zuul:
  routes:
    tens-base:
      path: /base/**
      serviceId: tens-base
    tens-qa:
      path: /qa/**
      serviceId: tens-qa
    tens-user:
      path: /user/**
      serviceId: tens-user
